### ISSUE TITLE
how does one get the benchmark corpus?

### ISSUE THREAD

**Issue by BurntSushi** [monolithpl/frequency-count-benchmark#1]
I see that there is a link to the corpus in the README, but it looks like the benchmarks were actually run with a `792 MB` sample. How might I reproduce that sample?

**Comment by monolithpl** [comment]
I used a custom version of the opensubtitles corpus that I couldn't share on github (due to file size limits).
to copy 792MB of a file do
dd if=OpenSubtitles2016.raw.en of=corpus.txt bs=792 MB count=1
(win32 version of dd here: http://www.chrysocome.net/downloads/dd-0.6beta3.zip
hope that helps!

**Comment by BurntSushi** [comment]
Excellent, a `dd` command is exactly what I was hoping for! (I figured the file was too big to practically host anywhere.) As a sanity check, the md5 hash for the resulting sample:

```
$ md5sum OpenSubtitles2016.raw.monolithpl.en 
a98b8c396b62a85a4db800fbb28ea2b4  OpenSubtitles2016.raw.monolithpl.en
```

(I'm asking because I'm about to publish a considerably thorough benchmark and wanted to do a sanity check with the only other good benchmark of these tools that I could find. Nice work. :-))

**Comment by monolithpl** [comment]
cool. do post a link to your benchmark once you're done - will be great to have a look!

**Comment by BurntSushi** [comment]
@monolithpl You can see my benchmark here: http://blog.burntsushi.net/ripgrep/ Enjoy!

**Comment by monolithpl** [comment]
thanks for the link! a fascinating read.
i was curious if rust could outpace c++, so i ran a mini benchmark on the binaries you provided (for both x86 and x64) versus the best tool from my benchmarks (the one here: https://github.com/monolithpl/frequency-count-benchmark/blob/master/binaries/grep7/grep.exe). on my computer, grep outperforms
- rg32 by 64% and rg64 by 32% on counting case-insensitive occurrences in a 700mb file (using `rg -c -i "fair game" corpus.txt`)
- rg32 by 51% and rg64 by 29% on counting case-sensitive occurrences in a 700mb file (using `rg -c "fair game" corpus.txt`)

i wonder if you would care to include these grep results in your benchmark? i realize that it would be counter-intuitive to include a tool that beats yours in your benchmark, but if you are comparing to grep - why not compare it to the fastest possible implementation out there (the ones that come with msys/git are somewhat underoptimized)?
it is perhaps a good idea to have independent benchmarks run by folks who don't have a stake in the game - that's the conclusion i came to after reviewing half a dozen benchmarks, most of them compiled by people who made the respective tools they themselves were benchmarking.
in any case, i'll be happy to update my frequency count benchmark with your tool.

**Comment by BurntSushi** [comment]
My benchmark is on Linux only. If I try your commands `rg -ci "fair game" corpus.txt` and `rg -c "fair game" corpus.txt` on my Windows 10 laptop, then I get 0.788s and 0.813s, respectively. For the analogous `grep` commands (using precisely the binary you linked), I get `0.962s` and `0.838s`, respectively. I used `ptime` to record the results. As a second data point, I get similar relative differences on my Windows 7 VM.

I ran each command several times and took the minimum time. I only tried `rg64`.

Some notes:
1. Your benchmark is limited to a simple literal. My benchmark is much much more comprehensive than that (but includes literals as well, both case sensitive and case insensitive).
2. The binaries I provide for Windows don't have SIMD support unfortunately, for $reasons. This will directly impact your benchmark for case insensitive matching.
3. I'm not familiar with Windows. While I'd be fine in principle with including something like, "benchmark results may differ on other platforms," I would absolutely not be comfortable with including actual numbers, because I don't know how to analyze them. I'm so unfamiliar with Windows that I don't even know how to extract a profile.
4. The GNU grep I benchmarked against was _not_ `msys/git`. It's not clear to me whether your `grep7` is actually the fastest possible implementation or not. The one on my Linux box might be faster, but that seems hard to know.
5. Your benchmark doesn't focus on end users. `ag` is, for example, not intended to be used in lieu of GNU grep for single-file searching. The author is pretty clear about this, so benchmarking _only that_ dimension is very misleading and doesn't really do much to disprove the author's claims. With that said, I understand where you're coming from, because a lot of the authors of these tools aren't upfront with their tools' shortcomings.

> i realize that it would be counter-intuitive to include a tool that beats yours in your benchmark

It's not counter-intuitive. `ripgrep` doesn't win every benchmark. More than that, performance isn't the only thing I measured. I also looked at correctness.

**Comment by BurntSushi** [comment]
> Your benchmark is limited to a simple literal. My benchmark is much much more comprehensive than that (but includes literals as well, both case sensitive and case insensitive).

This really matters by the way. `rg` achieves the biggest speed gains over GNU grep as the patterns get more complex. If you go and look at my single-file benchmarks closely, you'll see that on simple literals, most tools are relatively competitive with each other. As the patterns get more complex, so to does the difference between `rg` and other tools. I go into great detail explaining _why_ that is, too.

**Comment by BurntSushi** [comment]
> it is perhaps a good idea to have independent benchmarks run by folks who don't have a stake in the game

I would be shocked to discover if that were even possible. It took me years of experience to be capable of doing the analysis in my blog post. It's hard to get that without actually building something. Sometimes you just need to accept the bias as an inherent flaw (which I mentioned in my blog post) and interpret the data presented accordingly.

**Comment by monolithpl** [comment]
thanks for the exhaustive and informative reply. i concede right away that the scope of my benchmark is super limited (it just does what it says on the tin) - i was just referring to that section in your article where you also go into comparing case sensitive/insensitive counting. i'll look into trying to reproduce your timings - i am a bit puzzled that we would arrive at two opposite results, but then maybe it's just that apart from the human flaw (or bias) which you mention, there's also the impersonal software/hardware bias.
my benchmark project really just grew out of the frustration with the overhyped claims of the authors of ag, pt etc (surely there's a great difference between reading one 1 gb file and 1000 1mb files, but that's more up to low-level IO = filesystem + OS not the app itself).
my use case scenario is perfect for computational linguists who compile frequency lists of words from corpora, which might be different from parsing a directory structure full of code. 
in the end i guess you can just always put a footnote to any benchmark saying your mileage may vary and leave it at that. it was kind of you to share your knowledge on the subject.

**Comment by BurntSushi** [comment]
> i am a bit puzzled that we would arrive at two opposite results, but then maybe it's just that apart from the human flaw (or bias) which you mention

It happens. Most folks have been able to confirm my benchmarks for their data, but there are some that can't, and it isn't clear why. There are so many things that can impact performance, it's hard to say.

> (surely there's a great difference between reading one 1 gb file and 1000 1mb files, but that's more up to low-level IO = filesystem + OS not the app itself)

It's definitely up to the app quite a bit (in addition to the other things you mention). For example, `ag` and `ripgrep` will parallelize that search, where as `grep -r` won't. Moreover, `ag`/`ripgrep` will search a lot less by default than `grep -r` will, so doing that benchmark accurate is really hard. (Interestingly, searching less doesn't necessarily mean it's faster, because there's a lot of overhead associated with determining what _not_ to search. This feature of `ag`/`ripgrep` is really more about relevance than performance.)

To note, just because `ag`/`ripgrep` are parallelized doesn't mean they always win either, because parallelism doesn't always help. For example, I've been playing around with the `WebKit` git repo. Not including its `.git` directory, it has 2.7GB of files in it. Check out some comparisons. The first uses multiple threads, the second is forced to use one searcher thread, and the last is GNU grep (which is of course single threaded):

```
$ time rg ssl_open -g '*.cpp' 

real    0m0.328s
user    0m2.297s
sys     0m0.167s
$ time rg ssl_open -g '*.cpp' -j1

real    0m0.314s
user    0m0.433s
sys     0m0.170s
$ time grep ssl_open -r --include '*.cpp' 

real    0m0.318s
user    0m0.173s
sys     0m0.143s
```

In this case, parallelism basically does nothing for you. But if you run a query that need the regex engine to do real work, then it does help a lot:

```
[andrew@Cheetah WebKit] time rg -i '\w{60}' -g '*.cpp' -u | wc -l
520

real    0m0.413s
user    0m2.357s
sys     0m0.227s
[andrew@Cheetah WebKit] time rg -i '\w{60}' -g '*.cpp' -u -j1 | wc -l
520

real    0m1.030s
user    0m1.133s
sys     0m0.143s
[andrew@Cheetah WebKit] time LC_ALL=en_US.UTF-8 grep -E -i '\w{60}' -r --include '*.cpp' | wc -l
520

real    0m8.297s
user    0m8.177s
sys     0m0.120s
```

Notice how poorly GNU grep does here, mostly because it isn't fast when asked to support Unicode for some patterns, even though `ripgrep` supports Unicode. Even if we disable Unicode support in all the tools, we see that Rust's regex engine is indeed quite fast. It's so fast that parallelism doesn't help:

```
[andrew@Cheetah WebKit] time rg -i '(?-u)\w{60}' -g '*.cpp' -u | wc -l
520

real    0m0.288s
user    0m1.967s
sys     0m0.183s
[andrew@Cheetah WebKit] time rg -i '(?-u)\w{60}' -g '*.cpp' -u -j1 | wc -l
520

real    0m0.289s
user    0m0.400s
sys     0m0.153s
[andrew@Cheetah WebKit] time LC_ALL=C grep -E -i '\w{60}' -r --include '*.cpp' | wc -l
520

real    0m0.456s
user    0m0.320s
sys     0m0.133s
```

> my benchmark project really just grew out of the frustration with the overhyped claims of the authors of ag, pt etc

Somewhat agreed. I think the hype is kind of OK---it's OK to push your own tools---the thing I have a problem with is that the downsides of each tool aren't particularly well documented. My blog post tries to make a dent in that too.

> my use case scenario is perfect for computational linguists who compile frequency lists of words from corpora, which might be different from parsing a directory structure full of code. 
> in the end i guess you can just always put a footnote to any benchmark saying your mileage may vary and leave it at that. it was kind of you to share your knowledge on the subject.

Yeah, the thing about code is that it tends to be lots of very small files. In any case, thanks for your work on this benchmark. It was the only serious attempt I had seen on the Internet.

**Comment by monolithpl** [comment]
> the downsides of each tool aren't particularly well documented. My blog post tries to make a dent in that too.

indeed you have. thanks for the in-depth discussion, it's great to meet a like minded researcher.
